### ISSUE TITLE
Internet not working from the job?

### ISSUE THREAD

**Issue by drozzy** [ai4d-iasc/trixie#23] opened 2020-07-14 19:27 UTC
All of a sudden my logging (which uses weights and biases) stopped connecting to the wandb server:
(note it works fine on my local machine). 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/wandb/retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/wandb/apis/public.py", line 151, in execute
    return self._client.execute(*args, **kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/drozdyuka/.conda/envs/patchy_discs_model/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
wandb: Network error (ConnectionError), entering retry loop. See /gpfs/home/drozdyuka/patchy_discs_model/wandb/debug.log for full traceback.

```

**Comment by marctessier** [comment] 2020-07-15 02:51
The last time I tried this, Internet connectivity was only  available on the head node. I don't think Internet access was made available for the compute nodes.

**Comment by itamblyn** [comment] 2020-07-16 00:50
Was it working before? 

e.g. what changed?

**Comment by marctessier** [comment] 2020-07-16 01:05
I think this was by design / compromise. At first there was talks about no internet at all.. did not like that idea.. would have made things to difficult for many.

**Comment by drozzy** [comment] 2020-07-16 02:45
It was working before yes. On both the JobTesting and the TrixieMain.
I have experiments that have sent results to my logging service from both.

**Comment by NRCGavin** [comment] 2020-07-16 12:30
?As far as I can tell the internet is still working from the nodes.  The few I tested could all hit Google anyway.


Are you trying something other then port 80/443?


What URL are you trying to get to?


________________________________

**Comment by itamblyn** [comment] 2020-07-16 13:17
He is trying to use Weights and Biases. Looking at it, it may be an issue with the library or a port, @drozzy will get back you ...

**Comment by drozzy** [comment] 2020-07-19 16:16
I've no idea what library uses internally but it was working before.

To reproduce it, just install `wandb` with pip and try to call `wandb.init` in a python shell. Here is a full example:

```
$ pip install wandb
$ wandb login   <--- either create a https://www.wandb.com/ account or PM me for my key to give you temporarily.
$ python
>>> import wandb
>>> wandb.init()
```

Full instructions:
https://docs.wandb.com/quickstart#2-create-account

**Comment by drozzy** [comment] 2020-07-19 16:22
I can confirm internet works but not wandb logger. The same is true for both head node and worker nodes.

It was working before. I didn't change anything.

The same code works on my local machine.

To reproduce see my previous comment.

**Comment by drozzy** [comment] 2020-07-20 01:37
This is some issue with SSL.
Try running this:
`curl -v https://api.wandb.ai/healthz`

**Comment by drozzy** [comment] 2020-07-23 13:01
I got one helpful reply:

This looks like an SSL error where the machine doesn't support TLSv1.2. More information here: https://unix.stackexchange.com/questions/280548/curl-doesnt-connect-to-https-while-wget-does-nss-error-12286/310696#310696 You can likely fix with apt-get install nss or yum update nss

**Comment by ddamoursNRC** [comment] 2020-07-23 14:53
Site is being blocked from the network zone. Ticket filed to have rectified.

**Comment by ddamoursNRC** [comment] 2020-07-29 19:42
Usually requests are fixed within a day or two. As it has been almost a week I called in for an update. Hopefully this will be resolved by the end of the week.

**Comment by ddamoursNRC** [comment] 2020-07-31 12:38
Problem appears to be resolved. Please confirm and close this issue @drozzy

**Comment by itamblyn** [comment] 2020-09-10 12:43
Closing due to lack of answer from user (assuming it is resolved).

**Closed as completed by itamblyn** 2020-09-10 12:43 UTC
Labels: bug
