### ISSUE TITLE
Unable to use `sinfo` after 2023-06-21's maintenance

### ISSUE THREAD

**Issue by SamuelLarkin** [ai4d-iasc/trixie#93] opened 2023-06-21 17:14 UTC
After the electrical shutdown, I can no longer use `sinfo`
```bash
sinfo
slurm_load_partitions: Unable to contact slurm controller (connect failure)
```

**Comment by NRCGavin** [comment] 2023-06-22 11:15
At 11:53 yesterday slurmctld crashed due to resource issues on the headnode.  The resource issues appear to be the result of a python process that was submitted directly to the headnode.


Unfortunately the issue was not notice in time and the any jobs that had been submitted to the queue at that point have been terminated.


Slurmctld is back up and running and I am monitoring the situation.

________________________________
From: Samuel Larkin ***@***.***>
Sent: 21 June 2023 13:14:50
To: ai4d-iasc/trixie
Cc: Subscribed
Subject: [ai4d-iasc/trixie] Unable to use `sinfo` after 2023-06-21's maintenance (Issue #93)


***Attention*** This email originated from outside of the NRC. ***Attention*** Ce courriel provient de l'extérieur du CNRC.

After the electrical shutdown, I can no longer use sinfo

sinfo
slurm_load_partitions: Unable to contact slurm controller (connect failure)

**Comment by nrcfieldsa** [comment] 2023-06-26 18:19
Another trixie HPC user has reported this issue and have confirmed it myself.  The command they attempted and output was:
```
srun --x11 --pty --gres=gpu:4 bash -c 'watch -n 5 nvidia-smi & module load mathematica && mathematica'
 
srun: error: Unable to allocate resources: Unable to contact slurm controller (connect failure)
```

My attempt gave the same even when using: ```srun --pty /bin/bash -l```.  Just confirmed as of this time the slurmctld seems to have disappeared from the process list again on trixie-hn1.

**Comment by nrcfieldsa** [comment] 2023-09-19 21:39
Can you please close this issue, as it has been resolved since shortly after it was reported. If you still encounter an issue please add comment or let NRC KITS ITOps/RPS know.

**Closed as completed** 2023-09-20 12:31 UTC
